### ISSUE TITLE
Client Component Class Cast Exception: Unix 

### ISSUE THREAD

**Issue by JoeDezzy1** [tribotissues/tribotissues#62]
Description of the bug (be specific):

Exception in thread "AWT-EventQueue-1" java.lang.ClassCastException: obf.Kl cannot be cast to sun.lwawt.LWComponentPeer

This causes uneccessary CPU usage on Unix systems and is unfortunate for users with upper-scaled operations

How often the bug occurs:
It also happens every few seconds or so and prints it in the Client Debug Tab

Triggers of the bug (if known):
Switching between debug consoles, interacting with the UI, or just doing nothing. 
The exception gets semi-spammed in the debug and has been doing so for almost a year now. 

Does not occur on windows I have noticed.

Java version:
Java 8_151 and OracleJDK8

Max Heap Size:
386

TRiBot client version:
Latest

Looking Glass (yes/no):
No

Operating System:
Mac OS and Linux

Script Name:
Any script

TRiBot Old-School or RS3:
Old school

Client Debug:
[11:01:51] Exception in thread "AWT-EventQueue-1" 
[11:01:51] java.lang.**ClassCastException**: **obf.nk** cannot be cast to sun.lwawt.**LWComponentPeer**
[11:01:51] 	at sun.lwawt.LWRepaintArea.paintComponent(LWRepaintArea.java:57)
[11:01:51] 	at sun.awt.RepaintArea.paint(RepaintArea.java:240)
[11:01:51] 	at sun.lwawt.LWComponentPeer.handleJavaPaintEvent(LWComponentPeer.java:1314)
[11:01:51] 	at sun.lwawt.LWComponentPeer.handleEvent(LWComponentPeer.java:1198)
[11:01:51] 	**at obf.nk.handleEvent(qk:268)**
[11:01:51] 	at java.awt.Component.dispatchEventImpl(Component.java:4965)
[11:01:51] 	at java.awt.Component.dispatchEvent(Component.java:4711)
[11:01:51] 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
[11:01:51] 	at java.awt.EventQueue.access$500(EventQueue.java:97)
[11:01:51] 	at java.awt.EventQueue$3.run(EventQueue.java:709)
[11:01:51] 	at java.awt.EventQueue$3.run(EventQueue.java:703)
[11:01:51] 	at java.security.AccessController.doPrivileged(Native Method)
[11:01:51] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
[11:01:51] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
[11:01:51] 	at java.awt.EventQueue$4.run(EventQueue.java:731)
[11:01:51] 	at java.awt.EventQueue$4.run(EventQueue.java:729)
[11:01:51] 	at java.security.AccessController.doPrivileged(Native Method)
[11:01:51] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
[11:01:51] 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
[11:01:51] 	at **obf.Bj.dispatchEvent(of:525)**
[11:01:51] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
[11:01:51] 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
[11:01:51] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
[11:01:51] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
[11:01:51] 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[11:01:51] 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Bot Debug:
N/A

Screenshots (if any):

**Comment by iFluffee** [comment]
Same issue I discussed with you Todd.

**Comment by tribotissues** [comment]
This shouldn't be causing any CPU related spikes. 
Linux patch will be coming soon, however will only likely support Ubuntu and Gnome

**Comment by TRiLeZ** [comment]
Fixed in the latest release.
