### ISSUE TITLE
Severe client issues

### ISSUE THREAD

**Issue by FALSkills** [tribotissues/tribotissues#88]
Description of the bug (be specific):
The last tribot update introduced several severe client issues, which I will list all I know of currently below.

- Bot debug and client debug issues: 
Resizing either debug potentially crashes the client tab.
When the game window is blocked by the debugs, the bot mouse is unable to click the parts of the game window that are covered. Adjusting the debugs in this situation typically crashes the client tab.
Login.getLoginState throws a null pointer error.
[19:08:39] java.lang.NullPointerException
[19:08:39] 	at org.tribot.api.Screen.getDimension(fh:325)
[19:08:39] 	at org.tribot.api2007.Login.Fe(ni:4)
[19:08:39] 	at org.tribot.api2007.Login.getLoginState(ni:79)
[19:08:39] 	at obf.FJ.Un(qg:673)
[19:08:39] 	at obf.FJ.run(qg:782)
[19:08:39] 	at java.lang.Thread.run(Unknown Source)

- Loading issues
https://gyazo.com/8e4ee428f811134a0c4296374dcd326c
I haven't investigated this at all. Jagex had major server maintenance last week, maybe it is related.

- Miscellaneous other issues:
I hope that other users can add to this, as I have been out of town and unable to debug too much. I have noticed random issues with:
Player position being incorrect, 
Trading.getWindowState() returning that is is up when it is not, and 
godspower33 has noted that Players.find is not consistently working for him.

How often the bug occurs:
Debug issues are easy to replicate.
Loading issue is not very common. Could be connection related, unsure. I just know that it didn't happen previously.
I would need input from additional users to identify how often the miscellaneous other issues occur.

Triggers of the bug (if known):
Last tribot update
TRiBot Release 9.309_1 loaded. (1.8.0_45:C:\Program Files\Java\jdk1.8.0_45\jre)
Java version:
8u45, 8u111, 8u172
Max Heap Size:
512mb
TRiBot client version:
TRiBot Release 9.309_1
Looking Glass (yes/no):
no
Operating System:
Windows 10, Windows 8.1, Windows Server 2008
Script Name:
n/a
TRiBot Old-School or RS3:
Old-School
Client Debug:
n/a
Bot Debug:

[12:00:54] Error: av.jq() bl.iw() bl.iw() cw.hx() client.fk() client.ac() br.f() | ld:683 av:11293 bl:9404 bl:9505 cw:9269 client:4172 client:1653 br:408 br:362 Thread:745 | java.lang.ArrayIndexOutOfBoundsException: 56421
[12:00:55] error_game_crash
[12:00:55] Show document: http://oldschool86.runescape.com/error_game_crash.ws (_self)

[17:50:22] java.lang.NullPointerException
[17:50:22]     at org.tribot.api.Screen.getDimension(fh:325)
[17:50:22]     at org.tribot.api2007.Login.Fe(ni:4)
[17:50:22]     at org.tribot.api2007.Login.getLoginState(ni:79)
[17:50:22]     at obf.FJ.Un(qg:673)
[17:50:22]     at obf.FJ.run(qg:782)
[17:50:22]     at java.lang.Thread.run(Unknown Source)

Screenshots (if any):
only the gyazo above.

**Comment by FALSkills** [comment]
Here is an example of the poll interface (which is closed) being listed as open, which would coincide with the Trading.getWindowState() returning a non-null value even though it wasn't open.
https://gyazo.com/13aa99c41a6c55c7a1a839bfb71aa2a8

**Comment by FALSkills** [comment]
splitting this into multiple issues and closing this one.
