### ISSUE TITLE
Client loading issue

### ISSUE THREAD

**Issue by FALSkills** [tribotissues/tribotissues#95]
Description of the bug (be specific):
If the bot/client debug frames are pulled above the game window, the client cannot load the game.
How often the bug occurs:
Everytime
Triggers of the bug (if known):
Tribot resizable update TRiBot Release 9.309_1 loaded.
Java version:
8u45, 8u111
Max Heap Size:
512mb
TRiBot client version:
TRiBot Release 9.309_1 loaded.
Looking Glass (yes/no):
no
Operating System:
Windows 10, Windows 8, Windows server 2008
Script Name:
n/a
TRiBot Old-School or RS3:
old-school
Client Debug:
[19:44:37] Error: iw.i() client.ac() br.f() | iw:1148 client:1638 br:408 br:362 java.lang.Thread.run | java.lang.ArrayIndexOutOfBoundsException: 104051
[19:44:38] error_game_crash
[19:44:38] Show document: http://oldschool26.runescape.com/error_game_crash.ws (_self)
Bot Debug:
[17:50:22] java.lang.NullPointerException
[17:50:22] at org.tribot.api.Screen.getDimension(fh:325)
[17:50:22] at org.tribot.api2007.Login.Fe(ni:4)
[17:50:22] at org.tribot.api2007.Login.getLoginState(ni:79)
[17:50:22] at obf.FJ.Un(qg:673)
[17:50:22] at obf.FJ.run(qg:782)
[17:50:22] at java.lang.Thread.run(Unknown Source)
Screenshots (if any):

**Comment by FALSkills** [comment]
[14:46:27] TRiBot Release 9.310_0 loaded. (1.8.0_171:C:\Program Files (x86)\Java\jre1.8.0_171)
[14:46:28] Launching Client from Boot File
[14:46:28] Loading human mouse movement data.
[14:46:28] Successfully loaded human mouse data.
[14:46:36] Exception in thread "Thread-13" 
[14:46:36] java.lang.NullPointerException
[14:46:36] 	at obf.mk.run(zs:211)
[14:46:36] 	at java.lang.Thread.run(Unknown Source)
[14:46:37] Exception in thread "AWT-EventQueue-1" 
[14:46:37] java.lang.ArrayIndexOutOfBoundsException: 0
[14:46:37] 	at javax.swing.plaf.basic.BasicTabbedPaneUI.tabForCoordinate(Unknown Source)
[14:46:37] 	at javax.swing.plaf.basic.BasicTabbedPaneUI.setRolloverTab(Unknown Source)
[14:46:37] 	at javax.swing.plaf.basic.BasicTabbedPaneUI.access$2100(Unknown Source)
[14:46:37] 	at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mouseEntered(Unknown Source)
[14:46:37] 	at java.awt.AWTEventMulticaster.mouseEntered(Unknown Source)
[14:46:37] 	at java.awt.Component.processMouseEvent(Unknown Source)
[14:46:37] 	at javax.swing.JComponent.processMouseEvent(Unknown Source)
[14:46:37] 	at java.awt.Component.processEvent(Unknown Source)
[14:46:37] 	at java.awt.Container.processEvent(Unknown Source)
[14:46:37] 	at java.awt.Component.dispatchEventImpl(Unknown Source)
[14:46:37] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[14:46:37] 	at java.awt.Component.dispatchEvent(Unknown Source)
[14:46:37] 	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
[14:46:37] 	at java.awt.LightweightDispatcher.retargetMouseEnterExit(Unknown Source)
[14:46:37] 	at java.awt.LightweightDispatcher.trackMouseEnterExit(Unknown Source)
[14:46:37] 	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
[14:46:37] 	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
[14:46:37] 	at java.awt.Container.dispatchEventImpl(Unknown Source)
[14:46:37] 	at java.awt.Window.dispatchEventImpl(Unknown Source)
[14:46:37] 	at java.awt.Component.dispatchEvent(Unknown Source)
[14:46:37] 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
[14:46:37] 	at java.awt.EventQueue.access$500(Unknown Source)
[14:46:37] 	at java.awt.EventQueue$3.run(Unknown Source)
[14:46:37] 	at java.awt.EventQueue$3.run(Unknown Source)
[14:46:37] 	at java.security.AccessController.doPrivileged(Native Method)
[14:46:37] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[14:46:37] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[14:46:37] 	at java.awt.EventQueue$4.run(Unknown Source)
[14:46:37] 	at java.awt.EventQueue$4.run(Unknown Source)
[14:46:37] 	at java.security.AccessController.doPrivileged(Native Method)
[14:46:37] 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
[14:46:37] 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
[14:46:37] 	at obf.gj.RI(yn:692)
[14:46:37] 	at obf.gj.dispatchEvent(yn:617)
[14:46:37] 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
[14:46:37] 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
[14:46:37] 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
[14:46:37] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[14:46:37] 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
[14:46:37] 	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by TRiLeZ** [comment]
Fixed in latest release.
